### ISSUE TITLE
npm run build

### ISSUE THREAD

**Issue by 7u5a** [nxtedition/create-caspar-graphics#88]
When I do a npm run build, I get  a lot errors:

`
PS C:\CasparCG\Templates\my-graphics> npm run build

>my-graphics@0.0.0 build
>caspar-graphics build

Caspar Graphics v1.0.0-beta.28 building 5 templates...
Could not resolve entry module "templates/index.html".
✗ C:\CasparCG\Templates\my-graphics\templates
Error [RollupError]: Could not resolve entry module "templates/index.html".
    at error (file:///C:/CasparCG/Templates/my-graphics/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
    at ModuleLoader.loadEntryModule (file:///C:/CasparCG/Templates/my-graphics/node_modules/rollup/dist/es/shared/node-entry.js:18021:20)
    at async Promise.all (index 0) {
 code: 'UNRESOLVED_ENTRY'
}
Could not resolve entry module "index.html".
✗ C:\CasparCG\Templates\my-graphics
Error [RollupError]: Could not resolve entry module "index.html".
    at error (file:///C:/CasparCG/Templates/my-graphics/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
    at ModuleLoader.loadEntryModule (file:///C:/CasparCG/Templates/my-graphics/node_modules/rollup/dist/es/shared/node-entry.js:18021:20)
    at async Promise.all (index 0) {
  code: 'UNRESOLVED_ENTRY'
}
Could not resolve entry module "templates/**/index.html/index.html".
✗ C:\CasparCG\Templates\my-graphics\templates\**\index.html
Error [RollupError]: Could not resolve entry module "templates/**/index.html/index.html".
    at error (file:///C:/CasparCG/Templates/my-graphics/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
    at ModuleLoader.loadEntryModule (file:///C:/CasparCG/Templates/my-graphics/node_modules/rollup/dist/es/shared/node-entry.js:18021:20)
    at async Promise.all (index 0) {
  code: 'UNRESOLVED_ENTRY'
}
ENOENT: no such file or directory, mkdir 'C:\CasparCG\Templates\my-graphics\dist\C:\CasparCG\Templates\my-graphics\templates\example'
✗ C:\CasparCG\Templates\my-graphics\templates\example
[Error: ENOENT: no such file or directory, mkdir 'C:\CasparCG\Templates\my-graphics\dist\C:\CasparCG\Templates\my-graphics\templates\example'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: 'C:\\CasparCG\\Templates\\my-graphics\\dist\\C:\\CasparCG\\Templates\\my-graphics\\templates\\example'
}
ENOENT: no such file or directory, mkdir 'C:\CasparCG\Templates\my-graphics\dist\C:\CasparCG\Templates\my-graphics\templates\næste'
✗ C:\CasparCG\Templates\my-graphics\templates\næste
[Error: ENOENT: no such file or directory, mkdir 'C:\CasparCG\Templates\my-graphics\dist\C:\CasparCG\Templates\my-graphics\templates\næste'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: 'C:\\CasparCG\\Templates\\my-graphics\\dist\\C:\\CasparCG\\Templates\\my-graphics\\templates\\næste'
}
PS C:\CasparCG\Templates\my-graphics>
`

I do'nt know what causes that?

**Comment by tobiasandersen** [comment]
I just published a new version of caspar-graphics (`1.0.0-beta.29`) where this should hopefully be fixed. Could you give it a try?

**Comment by 7u5a** [comment]
Something works better now.
Still something is not okay, but it builds templates
`
Caspar Graphics v1.0.0-beta.29 building 2 templates...
✗ example
TypeError [ERR_INVALID_ARG_TYPE]: The "cb" argument must be of type function. Received undefined
    at makeCallback (node:fs:195:3)
    at Object.rename (node:fs:1015:14)
    at file:///C:/CasparCG/Templates/html-graphics/node_modules/@nxtedition/caspar-graphics/src/node/build.js:85:14
    at async Promise.all (index 0)
    at async build (file:///C:/CasparCG/Templates/html-graphics/node_modules/@nxtedition/caspar-graphics/src/node/build.js:70:3)
    at async CAC.<anonymous> (file:///C:/CasparCG/Templates/html-graphics/node_modules/@nxtedition/caspar-graphics/src/node/cli.js:65:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
✗ næste
TypeError [ERR_INVALID_ARG_TYPE]: The "cb" argument must be of type function. Received undefined
    at makeCallback (node:fs:195:3)
    at Object.rename (node:fs:1015:14)
    at file:///C:/CasparCG/Templates/html-graphics/node_modules/@nxtedition/caspar-graphics/src/node/build.js:85:14
    at async Promise.all (index 1)
    at async build (file:///C:/CasparCG/Templates/html-graphics/node_modules/@nxtedition/caspar-graphics/src/node/build.js:70:3)
    at async CAC.<anonymous> (file:///C:/CasparCG/Templates/html-graphics/node_modules/@nxtedition/caspar-graphics/src/node/cli.js:65:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
`

**Comment by tobiasandersen** [comment]
How about now? `1.0.0-beta.30`

**Comment by 7u5a** [comment]
Now it ran smooth.
![image](https://github.com/nxtedition/create-caspar-graphics/assets/89579091/3a1acb30-be00-4066-9c50-f4db7333fcc5)

Just have to test the template later on CasparCG.

**Comment by tobiasandersen** [comment]
Thanks for confirming. I'll go ahead and close the issue.

**Comment by 7u5a** [comment]
The template will not run:

> [2024-01-17 02:46:45.579] [error]   html[file://d:/template/EXAMPLE/INDEX.html] 1920 1080 50.000000 Log: Failed to load module script: The server responded with a non-JavaScript MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.
[2024-01-17 02:46:45.580] [error]   html[file://d:/template/EXAMPLE/INDEX.html] 1920 1080 50.000000 Log: Uncaught ReferenceError: update is not defined
[2024-01-17 02:46:45.580] [error]   html[file://d:/template/EXAMPLE/INDEX.html] 1920 1080 50.000000 Log: Uncaught ReferenceError: play is not defined
[2024-01-17 02:47:03.354] [info]    Received message from 127.0.0.1: CG 1-20 STOP 1\r\n
[2024-01-17 02:47:03.354] [info]    Sent message to 127.0.0.1:202 CG OK\r\n

**Comment by 7u5a** [comment]
But still the template won't play

> [2024-01-17 03:58:50.590] [info]    Received message from 127.0.0.1: CG 1-20 ADD 1 "EXAMPLE" 1 "<templateData><componentData id=\"name\"><data id=\"text\" value=\"Tue Sandbæk\"/></componentData></templateData>"\r\n
[2024-01-17 03:58:50.591] [info]    Sent message to 127.0.0.1:202 CG OK\r\n
[2024-01-17 03:58:50.594] [info]    html[file://d:/template/EXAMPLE.html] Destroyed.
[2024-01-17 03:58:50.652] [info]    html[file://d:/template/EXAMPLE.html] 1920 1080 50.000000 Log: parse failed:el is not defined
[2024-01-17 03:58:50.652] [info]    html[file://d:/template/EXAMPLE.html] 1920 1080 50.000000 Log: Yg.play()

> [2024-01-17 03:59:21.798] [info]    Received message from 127.0.0.1: CG 1-20 STOP 1\r\n
[2024-01-17 03:59:21.798] [info]    Sent message to 127.0.0.1:202 CG OK\r\n
[2024-01-17 03:59:21.799] [info]    html[file://d:/template/EXAMPLE.html] 1920 1080 50.000000 Log: Yg.stop()
[2024-01-17 03:59:21.799] [warning] html[file://d:/template/EXAMPLE.html] 1920 1080 50.000000 Log: GSAP target #name not found. https://gsap.com
